"""
WebSocket terminal — tmux-based with JWT authentication.

JWT is generated by the backend and passed as query parameter.
The orchestrator validates it on connect and attaches to a tmux session.

On disconnect: tmux keeps running, container alive (40-min timeout).
On reconnect: tmux reattaches with full scrollback preserved.
"""

import asyncio
import json
import logging

import aiodocker
import jwt
from fastapi import APIRouter, WebSocket, WebSocketDisconnect, Query

from app.config import JWT_ALGORITHM, JWT_SECRET
from app.api.labs import sessions

logger = logging.getLogger(__name__)

router = APIRouter(tags=["websocket"])


def _verify_token(token: str) -> dict | None:
    try:
        return jwt.decode(token, JWT_SECRET, algorithms=[JWT_ALGORITHM])
    except jwt.ExpiredSignatureError:
        logger.warning("WebSocket token expired")
        return None
    except jwt.InvalidTokenError as e:
        logger.warning(f"Invalid WebSocket token: {e}")
        return None


@router.websocket("/ws/{container_name}/terminal")
async def terminal(
    websocket: WebSocket,
    container_name: str,
    token: str = Query(...),
):
    # --- JWT validation ---
    claims = _verify_token(token)
    if not claims:
        await websocket.accept()
        await websocket.close(code=4001, reason="Invalid or expired token")
        return

    # Verify the container belongs to this session
    session_id = claims.get("session_id")
    session = sessions.get(session_id)
    if not session or session.container_name != container_name:
        await websocket.accept()
        await websocket.close(code=4003, reason="Session mismatch")
        return

    await websocket.accept()

    docker = aiodocker.Docker()
    try:
        container = await docker.containers.get(container_name)

        # Atomically create-or-attach: tries creating a new detached session
        # (fails silently if one already exists), then attaches regardless.
        # This avoids a race where two connections both check _tmux_exists
        # before either creates the session.
        # Initial size will be corrected by the first resize message from the
        # frontend (sent on connect), so a generous default is fine here.
        attach_cmd = [
            "bash", "-c",
            "tmux new-session -d -s lab '/bin/bash -l' 2>/dev/null; "
            "tmux attach-session -t lab",
        ]

        exec_obj = await container.exec(
            cmd=attach_cmd,
            stdin=True,
            stdout=True,
            stderr=True,
            tty=True,
            user="student",
        )
        stream = exec_obj.start(detach=False)

        async with stream:

            async def ws_to_exec():
                try:
                    while True:
                        # Accept both binary and text frames (the frontend sends
                        # terminal input as binary and resize as text/binary JSON).
                        message = await websocket.receive()
                        if message.get("type") != "websocket.receive":
                            continue
                        payload = message.get("bytes")
                        if payload is None:
                            text = message.get("text")
                            if text is None:
                                continue
                            payload = text.encode()
                        # Check for JSON resize messages
                        try:
                            msg = json.loads(payload.decode())
                            if msg.get("type") == "resize":
                                cols = msg["cols"]
                                rows = msg["rows"]
                                # Resize the attach exec's PTY so the attached
                                # tmux client reflows to the correct size. This
                                # is race-free: tmux follows the client size even
                                # while attach is still settling.
                                try:
                                    await exec_obj.resize(h=rows, w=cols)
                                except Exception as e:
                                    logger.debug(f"exec PTY resize failed: {e}")
                                await container.exec(
                                    ["tmux", "resize-window", "-t", "lab",
                                     "-x", str(cols), "-y", str(rows)],
                                    stdin=False, stdout=False, stderr=False,
                                )
                                continue
                        except (json.JSONDecodeError, UnicodeDecodeError):
                            pass
                        await stream.write_in(payload)
                except WebSocketDisconnect:
                    logger.info(f"WebSocket disconnected for '{container_name}'")
                except Exception as e:
                    logger.debug(f"ws_to_exec ended: {e}")

            async def exec_to_ws():
                try:
                    while True:
                        msg = await stream.read_out()
                        if msg is None:
                            break
                        await websocket.send_bytes(msg.data)
                except Exception as e:
                    logger.debug(f"exec_to_ws ended: {e}")

            send_task = asyncio.create_task(ws_to_exec())
            recv_task = asyncio.create_task(exec_to_ws())

            done, pending = await asyncio.wait(
                [send_task, recv_task],
                return_when=asyncio.FIRST_COMPLETED,
            )

            for task in pending:
                task.cancel()

    except Exception as e:
        logger.error(f"Terminal error for '{container_name}': {e}")
        try:
            await websocket.close(code=1011, reason="Internal error")
        except Exception:
            pass
    finally:
        await docker.close()
