"""
WebSocket terminal — tmux-based with JWT authentication.

JWT is generated by the backend and passed as query parameter.
The orchestrator validates it on connect and attaches to a tmux session.

On disconnect: tmux keeps running, container alive (40-min timeout).
On reconnect: tmux reattaches with full scrollback preserved.
"""

import asyncio
import logging

import aiodocker
import jwt
from fastapi import APIRouter, WebSocket, WebSocketDisconnect, Query

from app.config import JWT_ALGORITHM, JWT_SECRET
from app.api.labs import sessions

logger = logging.getLogger(__name__)

router = APIRouter(tags=["websocket"])


def _verify_token(token: str) -> dict | None:
    try:
        return jwt.decode(token, JWT_SECRET, algorithms=[JWT_ALGORITHM])
    except jwt.ExpiredSignatureError:
        logger.warning("WebSocket token expired")
        return None
    except jwt.InvalidTokenError as e:
        logger.warning(f"Invalid WebSocket token: {e}")
        return None


async def _tmux_exists(container) -> bool:
    """Check if a tmux session named 'lab' exists inside the container."""
    try:
        exec_obj = await container.exec(
            cmd=["tmux", "has-session", "-t", "lab"],
            stdin=False,
            stdout=False,
            stderr=False,
        )
        stream = exec_obj.start(detach=False)
        # Read until stream closes, then check exit code
        await stream.read_out()
        # aiodocker: inspect the exec to get exit code
        info = await exec_obj.inspect()
        return info.get("ExitCode", 1) == 0
    except Exception:
        return False


@router.websocket("/ws/{container_name}/terminal")
async def terminal(
    websocket: WebSocket,
    container_name: str,
    token: str = Query(...),
):
    # --- JWT validation ---
    claims = _verify_token(token)
    if not claims:
        await websocket.accept()
        await websocket.close(code=4001, reason="Invalid or expired token")
        return

    # Verify the container belongs to this session
    session_id = claims.get("session_id")
    session = sessions.get(session_id)
    if not session or session.container_name != container_name:
        await websocket.accept()
        await websocket.close(code=4003, reason="Session mismatch")
        return

    await websocket.accept()

    docker = aiodocker.Docker()
    try:
        container = await docker.containers.get(container_name)

        # Check if tmux session already exists (reconnect case)
        tmux_exists = await _tmux_exists(container)

        if tmux_exists:
            # Reconnect — attach to existing session
            attach_cmd = ["tmux", "attach-session", "-t", "lab"]
        else:
            # First connect — create new session with bash
            attach_cmd = [
                "tmux", "new-session", "-s", "lab",
                "-x", "200", "-y", "50",
                "/bin/bash", "-l",
            ]

        exec_obj = await container.exec(
            cmd=attach_cmd,
            stdin=True,
            stdout=True,
            stderr=True,
            tty=True,
            user="student",
        )
        stream = exec_obj.start(detach=False)

        async with stream:

            async def ws_to_exec():
                try:
                    while True:
                        data = await websocket.receive_bytes()
                        await stream.write_in(data)
                except WebSocketDisconnect:
                    logger.info(f"WebSocket disconnected for '{container_name}'")
                except Exception as e:
                    logger.debug(f"ws_to_exec ended: {e}")

            async def exec_to_ws():
                try:
                    while True:
                        msg = await stream.read_out()
                        if msg is None:
                            break
                        await websocket.send_bytes(msg.data)
                except Exception as e:
                    logger.debug(f"exec_to_ws ended: {e}")

            send_task = asyncio.create_task(ws_to_exec())
            recv_task = asyncio.create_task(exec_to_ws())

            done, pending = await asyncio.wait(
                [send_task, recv_task],
                return_when=asyncio.FIRST_COMPLETED,
            )

            for task in pending:
                task.cancel()

    except Exception as e:
        logger.error(f"Terminal error for '{container_name}': {e}")
        try:
            await websocket.close(code=1011, reason="Internal error")
        except Exception:
            pass
    finally:
        await docker.close()
