services:
  frontend:
    build:
      context: ./next-app
    container_name: sgp-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./next-app:/app
      - frontend_next:/app/.next
      - frontend_content:/app/.content
    extra_hosts:
      - "localhost.floci.io:host-gateway"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - NEXT_TELEMETRY_DISABLED=1
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:8000
      - BACKEND_API_URL=http://backend:8000
      - CONTENT_LOCAL_DIR=/app/.content
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build:
      context: ./backend
    container_name: sgp-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID:-}
      - FIREBASE_CREDENTIALS_JSON=${FIREBASE_CREDENTIALS_JSON:-}
      - CONTENT_PUBLIC_BASE_URL=${CONTENT_PUBLIC_BASE_URL:-http://localhost.floci.io:4566/my-content-bucket}
      - ORCHESTRATOR_URL=http://host.docker.internal:8001
      - WS_ORCHESTRATOR_URL=ws://host.docker.internal:8001
      - JWT_SECRET=${JWT_SECRET:-dev-only-change-in-production}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

  worker:
    build:
      context: ./worker
    container_name: sgp-worker
    ports:
      - "8002:8000"
    volumes:
      - ./worker:/app
      - worker_content:/data/content
      - ./backend/app/core/credentials.json:/app/credentials.json:ro
    extra_hosts:
      - "localhost.floci.io:host-gateway"
    environment:
      - CONTENT_DIR_S3=/data/content
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID:-}
      - FIREBASE_CREDENTIALS_JSON=${FIREBASE_CREDENTIALS_JSON:-}
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials.json
      - SYNC_INTERVAL_SECONDS=300
      - S3_BUCKET=my-content-bucket
      - AWS_ENDPOINT_URL=${AWS_ENDPOINT_URL:-http://localhost.floci.io:4566}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-test}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-test}
      - AWS_REGION=${AWS_REGION:-us-east-1}
    depends_on:
      - backend
    restart: unless-stopped

  floci:
    image: floci/floci:latest
    container_name: floci
    ports:
      - "4566:4566"

    environment:
      FLOCI_STORAGE_MODE: hybrid
      FLOCI_STORAGE_PERSISTENT_PATH: /app/data

    volumes:
      - floci-data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock

    restart: unless-stopped


volumes:
  frontend_next:
  frontend_content:
  worker_content:
  floci-data: