#!/usr/bin/env bash
# ──────────────────────────────────────────────────────────────
# install-orchestrator.sh — Run the orchestrator as a systemd service
# ──────────────────────────────────────────────────────────────
# The orchestrator is a HOST PROCESS inside the VM (not a Docker
# container), so the VM's Docker daemon is free to run only lab
# containers. The app source lives on the Vagrant synced folder
# (/opt/sgp/orchestrator); dependencies live in a venv OUTSIDE that
# folder so they never sync back to the host.
# ──────────────────────────────────────────────────────────────
set -euo pipefail
export DEBIAN_FRONTEND=noninteractive

ORCHESTRATOR_DIR="/opt/sgp/orchestrator"
VENV_DIR="/opt/sgp/venv-orchestrator"
ENV_FILE="/opt/sgp/orchestrator.env"
SERVICE_NAME="labops-orchestrator"
SERVICE_FILE="/etc/systemd/system/${SERVICE_NAME}.service"

# ── Environment (override via vagrant env or .env) ────────────
JWT_SECRET="${JWT_SECRET:-dev-only-change-in-production}"
JWT_LEEWAY_SECONDS="${JWT_LEEWAY_SECONDS:-30}"
LAB_PREFIX="${LAB_PREFIX:-labops-lab}"
DEMO_PREFIX="${DEMO_PREFIX:-labops-demo}"
LAB_TIMEOUT_MINUTES="${LAB_TIMEOUT_MINUTES:-40}"
DEMO_TIMEOUT_MINUTES="${DEMO_TIMEOUT_MINUTES:-30}"
ORCHESTRATOR_SECRET="${ORCHESTRATOR_SECRET:-local-dev-super-secret}"
MAX_CONCURRENT_LABS="${MAX_CONCURRENT_LABS:-1}"
PORT="${ORCHESTRATOR_PORT:-8000}"

echo "==> Ensuring /opt/sgp exists..."
mkdir -p /opt/sgp

echo "==> Installing Python 3 + venv tooling (apt)..."
apt-get update -y
apt-get install -y \
  python3 python3-venv python3-pip python3-dev build-essential

echo "==> Creating orchestrator virtualenv (outside the synced folder)..."
rm -rf "$VENV_DIR"
python3 -m venv "$VENV_DIR"
"$VENV_DIR/bin/pip" install --no-cache-dir --upgrade pip
"$VENV_DIR/bin/pip" install --no-cache-dir -r "$ORCHESTRATOR_DIR/requirements.txt"

echo "==> Preparing orchestrator environment file..."
if [ -f "/opt/sgp/environments/dev/orchestrator/.env.dev" ]; then
  echo "  - Using /opt/sgp/environments/dev/orchestrator/.env.dev config"
  cp "/opt/sgp/environments/dev/orchestrator/.env.dev" "$ENV_FILE"
  # Strip any Windows CRLF line endings
  sed -i 's/\r$//' "$ENV_FILE"
else
  cat > "$ENV_FILE" <<EOF
# Generated by provisioning/install-orchestrator.sh
DOCKER_HOST=unix:///var/run/docker.sock
CONTAINER_RUNTIME_MODE=sysbox
LAB_PREFIX=${LAB_PREFIX}
DEMO_PREFIX=${DEMO_PREFIX}
LAB_TIMEOUT_MINUTES=${LAB_TIMEOUT_MINUTES}
DEMO_TIMEOUT_MINUTES=${DEMO_TIMEOUT_MINUTES}
JWT_SECRET=${JWT_SECRET}
JWT_LEEWAY_SECONDS=${JWT_LEEWAY_SECONDS}
ORCHESTRATOR_SECRET=${ORCHESTRATOR_SECRET}
MAX_CONCURRENT_LABS=${MAX_CONCURRENT_LABS}
EOF
fi
chown root:vagrant "$ENV_FILE"
chmod 640 "$ENV_FILE"

echo "==> Writing systemd unit (${SERVICE_NAME}.service)..."
cat > "$SERVICE_FILE" <<EOF
[Unit]
Description=SGP Lab Orchestrator (host process; VM daemon reserved for lab containers)
After=network-online.target docker.service
Wants=network-online.target docker.service

[Service]
Type=simple
User=vagrant
Group=docker
WorkingDirectory=${ORCHESTRATOR_DIR}
EnvironmentFile=${ENV_FILE}
ExecStart=${VENV_DIR}/bin/uvicorn app.main:app --host 0.0.0.0 --port ${PORT} --loop uvloop --ws websockets --proxy-headers --reload
Restart=always
RestartSec=5
TimeoutStopSec=30

[Install]
WantedBy=multi-user.target
EOF

echo "==> Removing legacy container deployment (if present)..."
docker rm -f labops-orchestrator >/dev/null 2>&1 || true

echo "==> Enabling + starting service..."
systemctl daemon-reload
systemctl enable --now "$SERVICE_NAME"
systemctl restart "$SERVICE_NAME"

echo "==> Orchestrator is exposed on guest :${PORT} → host :8001."
echo "==> Logs:      vagrant ssh -c 'journalctl -fu ${SERVICE_NAME}'"
echo "==> Status:    vagrant ssh -c 'systemctl status ${SERVICE_NAME}'"
echo "==> Orchestrator installed successfully."